// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9fYU970MvmnUxgdP1qLMNpOEuYgmOC-s',
    appId: '1:920278493071:web:0b473b893c0fd79da58dfa',
    messagingSenderId: '920278493071',
    projectId: 'notesapp-1f904',
    authDomain: 'notesapp-1f904.firebaseapp.com',
    storageBucket: 'notesapp-1f904.appspot.com',
    measurementId: 'G-D223445F40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJpScdYQuUcK6YInaBbOtGhUlJny1__UY',
    appId: '1:920278493071:android:b0a6ad6c6f2e385aa58dfa',
    messagingSenderId: '920278493071',
    projectId: 'notesapp-1f904',
    storageBucket: 'notesapp-1f904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsBWrgnScExGYwvdMWWhJAFVHwb--HY2I',
    appId: '1:920278493071:ios:801181b943c001e8a58dfa',
    messagingSenderId: '920278493071',
    projectId: 'notesapp-1f904',
    storageBucket: 'notesapp-1f904.appspot.com',
    iosBundleId: 'com.example.noteFireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsBWrgnScExGYwvdMWWhJAFVHwb--HY2I',
    appId: '1:920278493071:ios:801181b943c001e8a58dfa',
    messagingSenderId: '920278493071',
    projectId: 'notesapp-1f904',
    storageBucket: 'notesapp-1f904.appspot.com',
    iosBundleId: 'com.example.noteFireApp',
  );
}
